POST http://192.168.43.41:2022/api/users/students/login HTTP/1.1
Content-Type: application/json

{
"username":"monzersmiledev",
"first_name" : "Monzer",
"last_name" : "Omer",
"profile_pic" : "",
"birth_date" : 0,
"email" : "nezonru87@yahoo.com",
"password" : "password",
"sex" : "male"
}